name: Daily Commit

permissions:
  contents: write

on:
  schedule:
    - cron: '30 2 * * *'  # Runs daily at 02:30 UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: 24f2005506@ds.study.iitm.ac.in
        run: |
          git config user.name "DevSync Bot"
          git config user.email "24f2005506@ds.study.iitm.ac.in"

      - name: Create or Update Daily Commit File
        run: |
          echo "Daily update: $(date)" >> daily_update.txt
          git add daily_update.txt
          git commit --allow-empty -m "Automated daily commit $(date)"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/aditya2785/daily_commit_tds.git
